"""
JUALIN.AI — Chat API Routes  
Send message → AI response → save to DB
Optimized: sequential safe DB calls, reduced context
"""
from fastapi import APIRouter, Depends, HTTPException, Request
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select, func
from pydantic import BaseModel
from typing import Optional
import uuid
import re
import time

from config import get_settings
from models.database import get_db
from models.user import User, UserTier
from models.conversation import Conversation, Message, MessageRole
from models.chat_analytics import ChatAnalytics
from api.routes_auth import get_current_user
from core.logging_config import get_logger

router = APIRouter()
settings = get_settings()
logger = get_logger(__name__)


# ── Pydantic Schemas ──

class ChatSendRequest(BaseModel):
    message: str
    session_id: Optional[str] = None
    seller_slug: str  # Which store to chat with


class ChatResponse(BaseModel):
    response: str
    session_id: str
    quota_exceeded: bool = False
    conversation_id: int = 0


class ConversationResponse(BaseModel):
    id: int
    session_id: str
    customer_name: str
    is_urgent: int
    message_count: int = 0
    last_message: str = ""
    created_at: str


# ── Helpers ──

def parse_product_line(line: str) -> tuple[str, int]:
    # e.g., "Baju Pink Satin x2" or "Baju Pink Satin x 2" or "Baju Pink Satin 2pcs" or "Baju Pink Satin (2 pcs)"
    qty_match = re.search(r'\s+x\s*(\d+)\b', line, re.IGNORECASE)
    if not qty_match:
        qty_match = re.search(r'\b(\d+)\s*pcs\b', line, re.IGNORECASE)
    if not qty_match:
        qty_match = re.search(r'\s+(\d+)$', line) # quantity at the end of line
        
    if qty_match:
        qty = int(qty_match.group(1))
        # remove quantity pattern from line to get the clean product name
        clean_name = line.replace(qty_match.group(0), "").strip()
        return clean_name, qty
    else:
        return line.strip(), 1


def parse_order_text(text: str) -> dict | None:
    # check if "ORDER CONFIRMED" is in text
    if "ORDER CONFIRMED" not in text:
        return None
    
    # regex extract fields
    nama_match = re.search(r'(?:Nama|Name)\s*:\s*(.+)', text, re.IGNORECASE)
    alamat_match = re.search(r'(?:Alamat|Address)\s*:\s*(.+)', text, re.IGNORECASE)
    hp_match = re.search(r'(?:HP|No HP|Phone|Telepon)\s*:\s*(.+)', text, re.IGNORECASE)
    
    if not (nama_match and alamat_match and hp_match):
        return None
        
    # extract products
    products_raw = []
    lines = text.split('\n')
    for line in lines:
        p_match = re.search(r'(?:Produk|Product)\s*:\s*(.+)', line, re.IGNORECASE)
        if p_match:
            products_raw.append(p_match.group(1).strip())
            
    if not products_raw:
        return None
        
    return {
        "customer_name": nama_match.group(1).strip(),
        "customer_address": alamat_match.group(1).strip(),
        "customer_phone": hp_match.group(1).strip(),
        "products_raw": products_raw
    }


async def check_quota(seller_id: int, db: AsyncSession) -> dict:
    """Check seller's chat quota for current month."""
    result = await db.execute(
        select(func.count(Conversation.id))
        .where(Conversation.seller_id == seller_id)
        .where(
            func.date_trunc("month", Conversation.created_at) == 
            func.date_trunc("month", func.now())
        )
    )
    used = result.scalar() or 0
    
    # Get seller tier
    seller_result = await db.execute(select(User).where(User.id == seller_id))
    seller = seller_result.scalar_one()
    
    limits = {
        UserTier.FREE: settings.QUOTA_FREE,
        UserTier.STARTER: settings.QUOTA_STARTER,
        UserTier.PRO: settings.QUOTA_PRO,
        UserTier.BISNIS: settings.QUOTA_BISNIS,
    }
    limit = limits.get(seller.tier, 50)
    
    return {
        "used": used,
        "limit": limit,
        "remaining": max(0, limit - used),
        "is_exceeded": used >= limit,
        "percentage": round(used / limit * 100) if limit > 0 else 100,
    }


async def maybe_create_order_from_ai_response(
    ai_response_text: str,
    seller: User,
    conversation: Conversation,
    session_id: str,
    db: AsyncSession,
) -> tuple[str, bool]:
    """
    Parse an AI-confirmed order, create it, reduce stock, update memory,
    and append the real payment link generated by the backend.
    """
    parsed = parse_order_text(ai_response_text)
    if not parsed:
        return ai_response_text, False

    try:
        # 1. Update conversation customer info
        conversation.customer_name = parsed["customer_name"]
        conversation.customer_phone = parsed["customer_phone"]
        db.add(conversation)
        await db.commit()

        # 2. Match products in database to get correct IDs & prices
        from models.product import Product
        prod_result = await db.execute(
            select(Product)
            .where(Product.seller_id == seller.id)
            .where(Product.is_active == 1)
        )
        all_seller_products = prod_result.scalars().all()

        items = []
        for raw_p in parsed["products_raw"]:
            clean_name, qty = parse_product_line(raw_p)
            clean_lower = clean_name.lower().strip()
            matched_prod = None

            for p in all_seller_products:
                if p.nama.lower().strip() == clean_lower:
                    matched_prod = p
                    break

            if not matched_prod:
                for p in all_seller_products:
                    product_name = p.nama.lower().strip()
                    if clean_lower in product_name or product_name in clean_lower:
                        matched_prod = p
                        break

            if matched_prod:
                items.append({
                    "product_id": matched_prod.id,
                    "nama": matched_prod.nama,
                    "qty": qty,
                    "harga": matched_prod.harga,
                })

        if not items:
            return (
                ai_response_text
                + "\n\nMaaf kak, produk di order belum berhasil dicocokkan dengan katalog. Admin akan cek manual ya 🙏",
                False,
            )

        # JUALIN OS: hormati harga deal negosiasi yang sudah 'accepted' di percakapan ini
        deal_states = []
        try:
            from services.agent_os.negotiation import apply_deal_prices
            deal_states = await apply_deal_prices(seller.id, conversation.id, items, db)
        except Exception as e:
            logger.warning(f"apply_deal_prices skipped: {e}")

        from ai.tools import tool_buat_order
        order_result = await tool_buat_order(
            seller_id=seller.id,
            customer_name=parsed["customer_name"],
            customer_phone=parsed["customer_phone"],
            customer_address=parsed["customer_address"],
            items=items,
            conversation_id=conversation.id,
            db=db,
        )

        if "error" in order_result:
            return (
                ai_response_text
                + f"\n\nMaaf kak, order belum bisa dibuat otomatis: {order_result['error']}. Admin akan bantu cek ya 🙏",
                False,
            )

        # Tandai deal ditunaikan + catat di activity feed Negotiator
        if deal_states:
            try:
                from services.agent_os.negotiation import mark_deals_fulfilled
                from models.agent_os import AgentRun
                mark_deals_fulfilled(deal_states, order_result["order_id"])
                db.add(AgentRun(
                    seller_id=seller.id, agent_role="negotiator", trigger="chat", status="done",
                    summary=f"Deal nego ditunaikan di Order #{order_result['order_id']}",
                    detail_json={"order_id": order_result["order_id"],
                                 "items": [{"product_id": s.product_id, "deal": s.current_offer} for s in deal_states]},
                    conversation_id=conversation.id, order_id=order_result["order_id"],
                ))
            except Exception as e:
                logger.warning(f"mark_deals_fulfilled skipped: {e}")

        # 3. Update customer memory after order
        try:
            from services.customer_memory import get_or_create_memory, update_memory_after_order
            memory, _ = await get_or_create_memory(
                seller_id=seller.id,
                session_id=session_id,
                db=db,
                phone=parsed["customer_phone"],
                name=parsed["customer_name"],
            )
            await update_memory_after_order(memory, items, order_result["total"], db)
        except Exception as e:
            logger.warning(f"Failed to update memory after order: {e}")

        payment_url = order_result.get("payment_url")
        payment_text = (
            f"\n\nOrder #{order_result['order_id']} berhasil dibuat."
            f"\nTotal: {order_result['formatted']}"
        )
        if payment_url:
            payment_text += (
                f"\nLink pembayaran resmi: {payment_url}"
                "\nSilakan pilih QRIS/VA di halaman pembayaran ya kak 🙏"
            )

        return ai_response_text + payment_text, True

    except Exception as e:
        logger.error(f"Order creation failed: {e}", exc_info=True)
        return (
            ai_response_text
            + "\n\nMaaf kak, order belum berhasil diproses otomatis. Admin akan bantu cek ya 🙏",
            False,
        )


# ── Endpoints ──

@router.post("/send", response_model=ChatResponse)
async def send_message(
    req: ChatSendRequest,
    request: Request,
    db: AsyncSession = Depends(get_db),
):
    """
    Customer sends a message → AI processes → returns response.
    Public endpoint (no auth needed — customers don't have accounts).
    """
    # ── Rate limit ──
    from core.rate_limit import check_rate_limit
    client_ip = request.client.host if request.client else "unknown"
    rl = await check_rate_limit(f"chat:{client_ip}", max_requests=settings.CHAT_RATE_LIMIT_PER_MIN, window_seconds=60)
    if not rl["allowed"]:
        raise HTTPException(status_code=429, detail="Terlalu banyak permintaan. Coba lagi nanti.")
    # Find seller by slug
    result = await db.execute(select(User).where(User.slug == req.seller_slug))
    seller = result.scalar_one_or_none()
    
    if not seller:
        raise HTTPException(status_code=404, detail="Toko tidak ditemukan")
    
    if not seller.ai_active:
        return ChatResponse(
            response="Maaf, toko ini sedang tidak aktif. Silakan coba lagi nanti ya 🙏",
            session_id=req.session_id or str(uuid.uuid4()),
            quota_exceeded=False,
        )
    
    # Check quota
    quota = await check_quota(seller.id, db)
    if quota["is_exceeded"]:
        return ChatResponse(
            response=f"Hai kak! Terima kasih sudah menghubungi {seller.nama_toko} 😊\n"
                     f"Saat ini penjual kami sedang tidak tersedia.\n"
                     f"Silakan hubungi langsung via {seller.no_hp or 'kontak toko'} ya kak! 🙏",
            session_id=req.session_id or str(uuid.uuid4()),
            quota_exceeded=True,
        )
    
    # Get or create conversation
    session_id = req.session_id or str(uuid.uuid4())
    
    result = await db.execute(
        select(Conversation)
        .where(Conversation.session_id == session_id)
        .where(Conversation.seller_id == seller.id)
    )
    conversation = result.scalar_one_or_none()
    
    if not conversation:
        conversation = Conversation(
            seller_id=seller.id,
            session_id=session_id,
        )
        db.add(conversation)
        await db.commit()
        await db.refresh(conversation)
    
    # Save customer message first
    customer_msg = Message(
        conversation_id=conversation.id,
        role=MessageRole.CUSTOMER,
        content=req.message,
    )
    db.add(customer_msg)
    await db.commit()
    
    # Load history + memory sequentially (AsyncSession is NOT safe for concurrent use)
    result = await db.execute(
        select(Message)
        .where(Message.conversation_id == conversation.id)
        .order_by(Message.created_at.desc())
        .limit(10)
    )
    history = list(reversed(result.scalars().all()))
    
    memory_context = ""
    try:
        from services.customer_memory import get_or_create_memory, format_memory_context
        memory, is_returning = await get_or_create_memory(
            seller_id=seller.id,
            session_id=session_id,
            db=db,
            phone=conversation.customer_phone or "",
            name=conversation.customer_name or "Customer",
        )
        memory_context = format_memory_context(memory, is_returning)
    except Exception as e:
        logger.warning(f"Memory lookup skipped: {e}")

    # JUALIN OS: kalau sudah ada deal accepted, LLM wajib tahu harga deal (bukan katalog)
    if settings.ENABLE_AGENT_OS:
        try:
            from services.agent_os.negotiation import get_deal_context
            memory_context += await get_deal_context(seller.id, conversation.id, db)
        except Exception as e:
            logger.warning(f"deal context skipped: {e}")
    
    # Generate AI response (with memory context injected)
    intent = "general"
    sales_stage = "greeting"
    response_start = time.monotonic()
    order_created = False
    ai_response_text = ""
    structured_used = False
    agent_os_handled = False

    # ── JUALIN OS: orkestrasi multi-agen (negosiasi dll.) ──
    if settings.ENABLE_AGENT_OS:
        try:
            from services.agent_os.orchestrator import agent_os_handle_turn
            os_result = await agent_os_handle_turn(
                seller=seller, conversation=conversation, message=req.message,
                history=history, db=db, memory_context=memory_context,
            )
            if os_result.get("handled"):
                ai_response_text = os_result["reply"]
                intent = os_result.get("intent", intent)
                sales_stage = os_result.get("stage", sales_stage)
                order_created = os_result.get("order_created", order_created)
                structured_used = True      # cegah parser order lama berjalan
                agent_os_handled = True
        except Exception as e:
            logger.warning(f"Agent OS turn skipped: {e}")

    # ── Try structured AI actions first if enabled ──
    if settings.ENABLE_AI_ACTIONS and not ai_response_text:
        try:
            from ai.agent import get_ai_structured_response
            from ai.actions import execute_ai_actions

            structured, intent, sales_stage = await get_ai_structured_response(
                message=req.message,
                seller_id=seller.id,
                conversation_history=history,
                seller_style=seller.ai_style,
                db=db,
                memory_context=memory_context,
            )
            ai_response_text = structured.reply
            structured_used = True

            # Execute actions in nested transaction
            if structured.actions:
                try:
                    action_results = await execute_ai_actions(
                        seller_id=seller.id,
                        actions=structured.actions,
                        db=db,
                        actor="ai",
                        user_message=req.message,
                    )
                    for ar in action_results:
                        if ar.get("type") == "create_order" and ar.get("success"):
                            order_created = True
                            ai_response_text += (
                                f"\n\nOrder #{ar['order_id']} berhasil dibuat."
                                f"\nTotal: Rp {ar['total']:,.0f}"
                            )
                            if ar.get("payment_url"):
                                ai_response_text += f"\nLink pembayaran: {ar['payment_url']}"
                        elif ar.get("type") == "create_order" and not ar.get("success"):
                            ai_response_text += (
                                "\n\nMaaf kak, order belum bisa dibuat otomatis karena "
                                "stok/produk perlu dicek. Admin akan bantu cek ya."
                            )
                        elif ar.get("type") == "send_payment_link" and ar.get("success") and ar.get("payment_url"):
                            ai_response_text += f"\n\nLink pembayaran: {ar['payment_url']}"
                except Exception as action_exc:
                    logger.warning(f"Structured action execution failed: {action_exc}")
        except (ValueError, Exception) as e:
            logger.warning(f"Structured AI failed, falling back to legacy: {e}")
            ai_response_text = ""
            structured_used = False

    # ── Fallback to legacy AI response ──
    if not ai_response_text:
        try:
            from ai.agent import get_ai_response
            ai_response_text, intent, sales_stage = await get_ai_response(
                message=req.message,
                seller_id=seller.id,
                conversation_history=history,
                seller_style=seller.ai_style,
                db=db,
                memory_context=memory_context,
            )
        except Exception as e:
            logger.error(f"AI Error: {e}", exc_info=True)
            ai_response_text = (
                f"Hai kak! Terima kasih sudah menghubungi {seller.nama_toko} 😊\n"
                f"Maaf, asisten kami sedang sibuk. Coba kirim pesan lagi ya kak!"
            )

        # Legacy order parser (only if structured didn't handle it)
        if not structured_used:
            ai_response_text, order_created = await maybe_create_order_from_ai_response(
                ai_response_text=ai_response_text,
                seller=seller,
                conversation=conversation,
                session_id=session_id,
                db=db,
            )

    response_time_ms = round((time.monotonic() - response_start) * 1000)
    
    # Save AI response
    ai_msg = Message(
        conversation_id=conversation.id,
        role=MessageRole.AI,
        content=ai_response_text,
    )
    db.add(ai_msg)

    # Track analytics
    analytics = ChatAnalytics(
        conversation_id=conversation.id,
        seller_id=seller.id,
        intent=intent,
        sales_stage=sales_stage,
        response_time_ms=response_time_ms,
        user_message_length=len(req.message),
        ai_response_length=len(ai_response_text),
        converted_to_order=order_created,
    )
    db.add(analytics)

    # ── Record usage event ──
    try:
        from core.metering import record_usage_event
        await record_usage_event(
            db, seller_id=seller.id, metric="chat.sent", quantity=1,
            source="chat", source_id=str(conversation.id),
            idempotency_key=f"chat.sent:{conversation.id}:{ai_msg.id}",
        )
    except Exception:
        pass  # metering should not block chat

    # ── JUALIN OS: catat aktivitas Pramuniaga untuk activity feed ──
    if settings.ENABLE_AGENT_OS and not agent_os_handled:
        try:
            from services.agent_os.orchestrator import record_sales_activity
            await record_sales_activity(seller.id, conversation.id, intent, sales_stage, order_created, db)
        except Exception:
            pass

    await db.commit()
    
    return ChatResponse(
        response=ai_response_text,
        session_id=session_id,
        conversation_id=conversation.id,
    )


@router.get("/history/{session_id}")
async def get_chat_history(
    session_id: str,
    db: AsyncSession = Depends(get_db),
):
    """Get all messages in a conversation."""
    result = await db.execute(
        select(Conversation).where(Conversation.session_id == session_id)
    )
    conversation = result.scalar_one_or_none()
    
    if not conversation:
        raise HTTPException(status_code=404, detail="Conversation not found")
    
    messages_result = await db.execute(
        select(Message)
        .where(Message.conversation_id == conversation.id)
        .order_by(Message.created_at)
    )
    messages = messages_result.scalars().all()
    
    return {
        "session_id": session_id,
        "messages": [
            {
                "id": m.id,
                "role": m.role.value,
                "content": m.content,
                "created_at": m.created_at.isoformat() if m.created_at else "",
            }
            for m in messages
        ]
    }


@router.get("/conversations")
async def list_conversations(
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    """List all conversations for the current seller (optimized: 1 query instead of N+1)."""
    from sqlalchemy import desc
    from sqlalchemy.orm import selectinload
    
    # Single query: fetch conversations with eager-loaded messages (BUG 12 FIX)
    result = await db.execute(
        select(Conversation)
        .where(Conversation.seller_id == current_user.id)
        .options(selectinload(Conversation.messages))
        .order_by(desc(Conversation.updated_at))
        .limit(50)
    )
    conversations = result.scalars().unique().all()
    
    response = []
    for conv in conversations:
        msgs = conv.messages or []
        last_msg = msgs[-1] if msgs else None
        
        response.append({
            "id": conv.id,
            "session_id": conv.session_id,
            "customer_name": conv.customer_name,
            "is_urgent": conv.is_urgent,
            "message_count": len(msgs),
            "last_message": last_msg.content[:100] if last_msg else "",
            "created_at": conv.created_at.isoformat() if conv.created_at else "",
        })
    
    return response


@router.get("/quota")
async def get_quota(
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    """Get current seller's quota usage."""
    return await check_quota(current_user.id, db)
